package com.alperen.cryptocurrencydemoapp.model.ticker

/**
 * Created by Alperen Erdoğan on 30.05.2024.
 */
data class TickerData(
    var _id: String = "",
    var id: Int = 0,
    var main_currency_id: Int = 0,
    var second_currency_id: Int = 0,
    var time_create: Int = 0,
    var time_update: Int = 0,
    var status: Int = 0,
    var name: String = "",
    var type: Int = 0,
    var open: Int = 0,
    var volume: Long = 0,
    var volume_world: String = "",
    var volume_second_world: String = "",
    var close: Int = 0,
    var high: Long = 0,
    var low: Long = 0,
    var percent: Double = 0.0,
    var percentW: Double = 0.0,
    var percentH: Double = 0.0,
    var rate: Long = 0,
    var logo: Any? = null,
    var main: MainData? = null,
    var volumes: Volumes? = null,
    var second: Second? = null,
    var commission_percent: Double = 0.0,
    var commission_percent_market: String = "",
    var min_amount: Double = 0.0,
    var fixed: Any? = null,
    var commission_min: Any? = null,
    var last_rate24: Long = 0,
    var last_rateW: Long = 0,
    var last_rateH: Long = 0,
    var type_update_time: Any? = null,
    var pair_type: Any? = null,
    var margin_leverage: Int = 0,
    var filters: ArrayList<Any>? = null,
    var ath: Int = 0,
    var atl: Int = 0,
    var ath_f: String = "",
    var atl_f: String = "",
    var open_f: String = "",
    var close_f: String = "",
    var high_f: String = "",
    var low_f: String = "",
    var rate_f: String = "",
    var last_rate24_f: String = "",
    var last_rateW_f: String = "",
    var last_rateH_f: String = "",
    var volume_f: String = "",
    var volume_second_world_f: String = "",
    var volume_world_f: String = ""
)